//! Integration tests for `ardur audit`.

use assert_cmd::Command;

#[test]
fn audit_secrets_finds_pattern() {
    let dir = tempfile::tempdir().expect("tempdir");
    let src = dir.path().join("src");
    std::fs::create_dir_all(&src).expect("create src");
    std::fs::write(
        src.join("config.rs"),
        "let api_key = \"sk-1234567890abcdef\";\n",
    )
    .expect("write config");

    let output = Command::cargo_bin("ardur")
        .expect("the `ardur` binary builds")
        .env("HOME", dir.path())
        .args(["audit", "secrets", src.to_str().unwrap()])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let stdout = String::from_utf8(output).expect("stdout utf8");
    assert!(stdout.contains("potential_secret"), "{stdout}");
}

#[test]
fn audit_sbom_from_lockfile() {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        dir.path().join("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
"#,
    )
    .expect("write lockfile");

    let output = Command::cargo_bin("ardur")
        .expect("the `ardur` binary builds")
        .env("HOME", dir.path())
        .current_dir(dir.path())
        .args(["audit", "sbom", "--lockfile", "Cargo.lock"])
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    let stdout = String::from_utf8(output).expect("stdout utf8");
    assert!(stdout.contains("serde"), "{stdout}");
}

#[test]
fn audit_run_writes_report() {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(
        dir.path().join("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"
"#,
    )
    .expect("write lockfile");

    Command::cargo_bin("ardur")
        .expect("the `ardur` binary builds")
        .env("HOME", dir.path())
        .current_dir(dir.path())
        .args(["audit", "run", dir.path().to_str().unwrap()])
        .assert()
        .success();

    let report = dir.path().join(".ardur").join("audit_report.json");
    assert!(report.exists(), "audit report should be written");
}
