#!/usr/bin/env python3
"""Generate site/content/docs/ from an allowlist of repo docs (#515 S1).

The public docs section is a GENERATED COPY, not a mount: docs/ keeps mixed
formats and internal working documents, and only product-facing pages from
the explicit allowlist below are published. Copying happens at site
generation time (site-deploy.yml, before hugo), so the repo's docs/ stays
the single source — a docs PR is live on the site within one merge, with no
duplicated content to drift.

Design invariants (issue #515 §2 /docs, decision E1; review finding F2):

* Explicit allowlist only — new docs are NOT published by default; adding
  one is a reviewed code change to ALLOWED_DOCS.
* Frontmatter is injected (title from the first H1; description from the
  first paragraph); repo docs carry no Hugo frontmatter and stay unchanged.
* Local-only content must be impossible to publish: paths under
  .context/, architect/, agent session files, EXTENDED paths, and private
  tracker internals are rejected by a pattern guard (pinned by tests).
* Deterministic: identical inputs -> identical output for the .md files
  (per-file headers carry the source path, not a timestamp — a timestamp
  would defeat drift checking); the regeneration timestamp lives in the
  .generated sentinel, which --check excludes. Stale generated files whose
  source vanished are pruned.
* The output directory is gitignored: the repo's docs/ is the single
  source, generation happens in CI before hugo, and hand-edits to the
  copy cannot be committed at all.

Usage:
    python3 scripts/site-docs.py [--repo-root DIR] [--check]

--check verifies a fresh generation matches what is on disk (CI guard
against hand-edits and drift), exiting 1 on mismatch.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import shutil
import sys
from pathlib import Path

GENERATED_BY = "scripts/site-docs.py"
GENERATED_NOTE = f"generated by {GENERATED_BY} at {{ts}} — do not hand-edit"

OUTPUT_DIR = Path("site") / "content" / "docs"
SENTINEL_NAME = ".generated"

# Allowlist: repo-relative source -> site URL slug under /docs/.
# Product-facing pages only. Internal working documents (agent session
# conduct, competitive surveys, design-lane ADRs, internal roadmaps) stay
# repo-only by deliberate choice (plan #515 editorial rules; E1 default).
ALLOWED_DOCS: dict[str, str] = {
    "docs/benchmarks.md": "benchmarks",
    "docs/current-status.md": "current-status",
    "docs/device-mesh-control-plane.md": "device-mesh-control-plane",
    "docs/fresh-machine.md": "fresh-machine",
    "docs/loop-detector.md": "loop-detector",
    "docs/marketplace.md": "marketplace",
    "docs/project-surface.md": "project-surface",
    "docs/session-lifecycle.md": "session-lifecycle",
}

# Anything matching these patterns can never be published, allowlist or not.
FORBIDDEN_PATH_PATTERNS = (
    re.compile(r"(^|/)\.context(/|$)"),
    re.compile(r"(^|/)architect(/|$)"),
    re.compile(r"(^|/)plans(/|$)"),
    re.compile(r"(^|/)dev-workspace(/|$)"),
    re.compile(r"(^|/)handoff(/|$)"),
    # Agent session journals/notes (e.g. 2026-09-17-site-s0-journal.md),
    # not product docs that merely mention sessions (session-lifecycle.md).
    re.compile(r"(^|/)\d{4}-\d{2}-\d{2}-[^/]*session[^/]*\.md$"),
    re.compile(r"(^|/)session-journal"),
    re.compile(r"(^|/)EXTENDED(/|$)"),
    re.compile(r"/Volumes/"),
)


class DocsError(RuntimeError):
    pass


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def is_forbidden(path: str) -> bool:
    return any(p.search(path) for p in FORBIDDEN_PATH_PATTERNS)


def yaml_scalar(value: str) -> str:
    """YAML-safe double-quoted scalar (JSON strings are valid YAML 1.2
    double-quoted scalars; review finding on #528)."""
    return json.dumps(value, ensure_ascii=False)


REPO_FILE_URL = "https://github.com/ArdurAI/ardur-agent/blob/dev/"

# Allowlisted-doc filename -> site slug (for cross-doc link rewriting).
SLUG_BY_FILENAME = {
    Path(src).name: slug for src, slug in ALLOWED_DOCS.items()
}

LINK_RE = re.compile(r"(?P<prefix>[\[<][^]>\n]*[\]>]\()\s?(?P<href>[^)\s]+)\)?")


def rewrite_link(href: str, src_rel: str) -> str:
    """Rewrite a repo-relative link for its generated page (#528 P2).

    - Links to another allowlisted doc point at that page's site slug
      (site-relative so they work under any baseURL).
    - Links to other repository files point at the canonical GitHub view
      so they resolve instead of 404ing under /docs/.
    - External/anchor/absolute links pass through unchanged.
    """
    if href.startswith(("http://", "https://", "#", "mailto:", "/")):
        return href
    href_path = href.split("#", 1)[0].split("?", 1)[0]
    if not href_path:
        return href
    resolved = (Path(src_rel).parent / href_path).as_posix()
    resolved = re.sub(r"^\./", "", resolved)
    # Collapse ./ and ../ lexically (POSIX-style, no filesystem access).
    parts: list[str] = []
    for part in resolved.split("/"):
        if part == "." or part == "":
            continue
        if part == "..":
            if parts:
                parts.pop()
            continue
        parts.append(part)
    normalized = "/".join(parts)
    slug = ALLOWED_DOCS.get(normalized)
    if slug is not None:
        return f"../{slug}/"
    target_name = Path(normalized).name
    if target_name in SLUG_BY_FILENAME and "/" not in normalized.rstrip("/"):
        return f"../{SLUG_BY_FILENAME[target_name]}/"
    if normalized:
        return f"{REPO_FILE_URL}{normalized}"
    return href


def extract_title(body: str) -> str:
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and len(stripped) > 2:
            return stripped[2:].strip()
    return "Untitled"


def extract_description(body: str, limit: int = 220) -> str:
    """First non-heading, non-quote, non-code paragraph, flattened."""
    in_code = False
    for block in body.split("\n\n"):
        text = block.strip()
        if not text:
            continue
        if text.startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if text.startswith(("#", ">", "|", "-", "*", "1.")):
            continue
        flattened = re.sub(r"\s+", " ", text)
        if len(flattened) > limit:
            flattened = flattened[: limit - 1].rstrip() + "…"
        return flattened
    return "Ardur engineering documentation."


def transform(source: Path, body: str, src_rel: str) -> str:
    """Strip the leading H1 and rewrite repo-relative links (#528 P2).

    Link rewriting skips fenced code blocks; HTML <a href> links are
    handled by the same href rule.
    """
    lines = transform_strip_h1(body).splitlines()
    out: list[str] = []
    in_code = False
    for line in lines:
        if line.strip().startswith("```"):
            in_code = not in_code
            out.append(line)
            continue
        if not in_code:
            line = MD_LINK_RE.sub(
                lambda m: f"{m.group('prefix')}{rewrite_link(m.group('href'), src_rel)})",
                line,
            )
        out.append(line)
    return "\n".join(out)


def transform_strip_h1(body: str) -> str:
    lines = body.splitlines()
    for index, line in enumerate(lines):
        if line.strip().startswith("# "):
            return "\n".join(lines[index + 1 :]).lstrip("\n")
    return body


MD_LINK_RE = re.compile(r"(?P<prefix>\[[^\]\n]*\]\()\s?(?P<href>[^)\s]+)\)?")


def generate(repo_root: Path) -> list[str]:
    output_dir = repo_root / OUTPUT_DIR
    ts = utc_now()
    written: list[str] = []
    for src_rel, slug in sorted(ALLOWED_DOCS.items()):
        if is_forbidden(src_rel):
            raise DocsError(f"allowlist entry {src_rel!r} matches a forbidden pattern")
        source = repo_root / src_rel
        if not source.is_file():
            raise DocsError(f"allowlisted doc missing: {src_rel}")
        # A symlink at an allowlisted path could point outside the repo or
        # into a forbidden directory; the literal path check alone would not
        # catch it (#528 P2). Resolve and re-check.
        resolved = source.resolve()
        try:
            resolved_rel = resolved.relative_to(repo_root.resolve()).as_posix()
        except ValueError as exc:
            raise DocsError(
                f"allowlisted doc {src_rel!r} resolves outside the repository"
            ) from exc
        if is_forbidden(resolved_rel):
            raise DocsError(
                f"allowlisted doc {src_rel!r} resolves to forbidden path {resolved_rel!r}"
            )
        body = source.read_text(encoding="utf-8")
        title = extract_title(body)
        description = extract_description(body)
        frontmatter = (
            "---\n"
            f"title: {yaml_scalar(title)}\n"
            f"description: {yaml_scalar(description)}\n"
            f"layout: docs\n"
            f"slug: {yaml_scalar(slug)}\n"
            f"weight: {len(written) + 1}\n"
            "---\n\n"
            f"<!-- generated by {GENERATED_BY} from {src_rel} — do not "
            "hand-edit; regenerate with scripts/site-docs.py -->\n\n"
        )
        target = output_dir / f"{slug}.md"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(
            frontmatter + transform(source, body, src_rel), encoding="utf-8"
        )
        written.append(slug)
    # Prune stale generated files (renamed/removed allowlist entries). The
    # committed section index (_index.md) is NOT generated — keep it.
    expected = (
        {f"{slug}.md" for slug in ALLOWED_DOCS.values()}
        | {SENTINEL_NAME, "_index.md"}
    )
    for stale in output_dir.glob("*.md"):
        if stale.name not in expected:
            stale.unlink()
    (output_dir / SENTINEL_NAME).write_text(
        f"generated by {GENERATED_BY} at {ts} — do not hand-edit\n"
        f"allowlist: {len(ALLOWED_DOCS)} docs\n",
        encoding="utf-8",
    )
    return written


def check(repo_root: Path) -> bool:
    """True iff a fresh in-place generation changes nothing on disk.

    The sentinel is excluded: it legitimately carries the regeneration
    timestamp, while the .md bodies must be byte-deterministic.
    """
    output_dir = repo_root / OUTPUT_DIR
    before = {
        p.name: p.read_text(encoding="utf-8")
        for p in sorted(output_dir.glob("*.md"))
        if p.is_file()
    }
    generate(repo_root)
    after = {
        p.name: p.read_text(encoding="utf-8")
        for p in sorted(output_dir.glob("*.md"))
        if p.is_file()
    }
    return before == after


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 unless a fresh generation matches the files on disk",
    )
    args = parser.parse_args(argv)
    try:
        if args.check:
            if check(args.repo_root):
                print("docs generation matches disk (no drift)")
                return 0
            print(
                "docs generation DRIFTED from disk — regenerate with "
                "scripts/site-docs.py (hand-edits are not the source of truth)",
                file=sys.stderr,
            )
            return 1
        written = generate(args.repo_root)
        print(f"generated {len(written)} docs pages: {', '.join(written)}")
        return 0
    except DocsError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
