#!/usr/bin/env python3
"""Generate site/data/progress.json — the data behind the /status page.

Collects public evidence about the state of the project:

* GitHub public surface (open issues/PRs, latest green CI run on dev with
  test totals, latest release) via the REST API — the ``gh`` CLI when
  available (authenticated locally, token-authenticated in CI via GH_TOKEN),
  unauthenticated api.github.com as a fallback,
* a snapshot of the local beads board (ids/titles/statuses only, never
  comments or descriptions). bd and its .beads database are local-only, so
  the committed snapshot site/data/beads-snapshot.json is refreshed whenever
  a local run has bd available and carried forward (marked with its age)
  otherwise.

Design invariants (issue #515 §3.1, §6):

* Deterministic: identical inputs produce identical output.
* Fails loudly on missing sources under --strict instead of emitting stale
  data silently. Data that can only be carried forward is marked with its
  own regeneration timestamp — never presented as fresh.
* Allowlists public sources only: no secrets, no private issue bodies, no
  tracker comments. Beads contribute {id, title, status} exclusively.
* Generated files carry a "generated by scripts/site-progress.py" marker.

Usage:
    python3 scripts/site-progress.py [--repo-root DIR] [--output DIR] [--strict]

Exit codes: 0 success, 1 fatal (missing/failing source under --strict).
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

GENERATED_BY = "scripts/site-progress.py"
GENERATED_NOTE = f"generated by {GENERATED_BY} — do not hand-edit"

GITHUB_API = "https://api.github.com"

# Tracker statuses considered finished; finished items stay off /status.
BEADS_DONE_STATUSES = {"closed", "done"}

# Gauntlet job whose libtest lines are summed for the test totals.
CI_TEST_JOB = "ubuntu-latest / stable"
# The workflows API accepts the workflow's bare file name (not its path).
CI_WORKFLOW_FILE = "ci.yml"
CI_BRANCH = "dev"

# How many recent open issues/PRs become individual entries.
ENTRY_LIMIT = 20

BEADS_ROW_KEYS = ("id", "title", "status")


class CollectorError(RuntimeError):
    """Fatal collection error; under --strict the run aborts with exit 1."""


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def run(cmd: list[str], cwd: Path | None = None) -> str:
    """Run a command and return stdout; raise CollectorError on failure."""
    try:
        proc = subprocess.run(
            cmd,
            cwd=str(cwd) if cwd else None,
            capture_output=True,
            text=True,
            timeout=120,
        )
    except FileNotFoundError as exc:
        raise CollectorError(f"required tool not found: {cmd[0]!r}") from exc
    except subprocess.TimeoutExpired as exc:
        raise CollectorError(f"command timed out: {' '.join(cmd)}") from exc
    if proc.returncode != 0:
        detail = (proc.stderr or proc.stdout or "").strip()[:500]
        raise CollectorError(
            f"command failed ({proc.returncode}): {' '.join(cmd)}\n{detail}"
        )
    return proc.stdout


def git_repo_slug(repo_root: Path) -> str:
    """Return the 'owner/name' slug for the origin remote."""
    url = run(["git", "config", "--get", "remote.origin.url"], cwd=repo_root)
    match = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?$", url.strip())
    if not match:
        raise CollectorError(f"cannot parse owner/repo from remote: {url!r}")
    return match.group(1)


def gh_api(
    path: str,
    repo_root: Path | None = None,
    accept: str = "application/vnd.github+json",
) -> object:
    """GET a GitHub API path via the gh CLI, falling back to unauthenticated.

    CI checkouts have no stored gh credentials, so the workflow maps the job
    token into GH_TOKEN (gh picks it up automatically). The unauthenticated
    fallback keeps read-only collection working elsewhere, within the
    60 req/h shared limit.
    """
    gh_error: Exception | None = None
    if shutil.which("gh") is not None:
        try:
            raw = run(
                ["gh", "api", path, "-H", f"Accept: {accept}"],
                cwd=repo_root,
            )
            return json.loads(raw)
        except (CollectorError, json.JSONDecodeError) as exc:
            gh_error = exc  # fall through to the unauthenticated request
    url = (
        path
        if path.startswith("http")
        else f"{GITHUB_API}/{path.lstrip('/')}"
    )
    req = urllib.request.Request(url, headers={"Accept": accept})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except (urllib.error.URLError, json.JSONDecodeError, OSError) as exc:
        detail = f" (gh attempt failed first: {gh_error})" if gh_error else ""
        raise CollectorError(
            f"GitHub API request failed: {url}{detail}"
        ) from exc


# ---------------------------------------------------------------------------
# Beads board


def load_beads_snapshot(repo_root: Path) -> dict | None:
    path = repo_root / "site" / "data" / "beads-snapshot.json"
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise CollectorError(f"invalid beads snapshot {path}: {exc}") from exc


def write_beads_snapshot(repo_root: Path, items: list[dict]) -> dict:
    snapshot = {
        "_note": f"{GENERATED_NOTE} (local bd refresh)",
        "regenerated_at": utc_now(),
        "items": [
            {key: item.get(key) for key in BEADS_ROW_KEYS}
            for item in sorted(
                items, key=lambda i: (str(i.get("id", "")), str(i.get("title", "")))
            )
        ],
    }
    path = repo_root / "site" / "data" / "beads-snapshot.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(snapshot, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    return snapshot


def collect_beads(repo_root: Path) -> tuple[list[dict], dict]:
    """Return (items, source_meta) for the beads board.

    items is the raw allowlisted rows [{id, title, status}] for ALL beads;
    callers filter finished ones out for display. source_meta records whether
    the data is fresh (bd ran now) or a carried-forward snapshot, with its
    own regeneration timestamp so it is never presented as current.
    """
    if shutil.which("bd") is not None:
        try:
            raw = run(["bd", "list", "--json"], cwd=repo_root)
            parsed = json.loads(raw)
            rows = [
                {key: item.get(key) for key in BEADS_ROW_KEYS}
                for item in parsed
                if item.get("id") and item.get("title")
            ]
            snapshot = write_beads_snapshot(repo_root, parsed)
            return rows, {
                "fresh": True,
                "regenerated_at": snapshot["regenerated_at"],
                "note": "refreshed from bd in this run",
                "item_count": len(rows),
            }
        except (CollectorError, json.JSONDecodeError, KeyError) as exc:
            # bd present but unusable here (e.g. no .beads database in this
            # checkout — forks and CI). Degrade to the committed snapshot,
            # marked stale; only a missing snapshot is fatal below. The note
            # stays a fixed string: command diagnostics (paths, config
            # details) must not leak into generated public metadata.
            print(f"warning: bd list failed: {exc}", file=sys.stderr)
            snapshot = load_beads_snapshot(repo_root)
            if snapshot is None:
                raise CollectorError("bd list failed in this checkout") from exc
            return snapshot.get("items", []), {
                "fresh": False,
                "regenerated_at": snapshot.get("regenerated_at"),
                "note": (
                    "bd unavailable in this checkout; "
                    "carried-forward committed snapshot"
                ),
                "item_count": len(snapshot.get("items", [])),
            }
    snapshot = load_beads_snapshot(repo_root)
    if snapshot is None:
        raise CollectorError(
            "bd unavailable and no committed beads snapshot at "
            "site/data/beads-snapshot.json — run locally with bd installed "
            "to refresh the snapshot"
        )
    return snapshot.get("items", []), {
        "fresh": False,
        "regenerated_at": snapshot.get("regenerated_at"),
        "note": (
            "bd not available here; carried-forward snapshot from the "
            "committed file (refreshed by a local run)"
        ),
        "item_count": len(snapshot.get("items", [])),
    }


# ---------------------------------------------------------------------------
# GitHub public surface


def search_issues(slug: str, kind: str) -> tuple[int, list[dict]]:
    query = f"repo:{slug}+type:{kind}+state:open"
    data = gh_api(
        f"search/issues?q={query}&sort=updated&order=desc"
        f"&per_page={ENTRY_LIMIT}"
    )
    if not isinstance(data, dict):
        raise CollectorError(f"unexpected search response for {kind}")
    items = [
        {
            "number": item.get("number"),
            "title": item.get("title"),
            "html_url": item.get("html_url"),
            "updated_at": item.get("updated_at"),
        }
        for item in data.get("items", [])
        if item.get("number") and item.get("title")
    ]
    return int(data.get("total_count", 0)), items


def fetch_job_log(slug: str, job_id: int) -> str:
    """Download a CI job log, following the 302 to the backing blob.

    Deliberately not `gh api`: job logs contain ANSI escape sequences, and
    newer gh releases refuse to print them to a piped stdout unless given
    --allow-escape-sequences (observed on the site-deploy runner) — a
    version-dependent flag. A plain request with redirect-following works
    everywhere; GH_TOKEN (job token in CI) authenticates when present.

    The redirect target (a signed blob URL) carries its own auth in the
    query string, so the Authorization header is dropped on cross-host
    redirects — forwarding it makes the blob reject the request.
    """

    class _NoAuthRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, req, fp, code, msg, headers, newurl):
            redirected = super().redirect_request(req, fp, code, msg, headers, newurl)
            if redirected is not None and redirected.host != req.host:
                redirected.headers.pop("Authorization", None)
                redirected.unredirected_hdrs.pop("Authorization", None)
            return redirected

    url = f"{GITHUB_API}/repos/{slug}/actions/jobs/{job_id}/logs"
    headers = {"Accept": "application/vnd.github+json"}
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token and shutil.which("gh") is not None:
        try:
            token = run(["gh", "auth", "token"]).strip()
        except CollectorError:
            token = None
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, headers=headers)
    opener = urllib.request.build_opener(_NoAuthRedirect)
    try:
        with opener.open(req, timeout=120) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except (urllib.error.URLError, OSError) as exc:
        raise CollectorError(f"job log request failed: {url}") from exc


def collect_ci(slug: str, with_logs: bool) -> dict:
    """Latest successful CI run on dev, plus gauntlet test totals."""
    runs = gh_api(
        f"repos/{slug}/actions/workflows/{CI_WORKFLOW_FILE}/runs"
        f"?branch={CI_BRANCH}&status=success&per_page=5"
    )
    if not isinstance(runs, dict) or not runs.get("workflow_runs"):
        raise CollectorError(
            f"no successful CI runs found on branch {CI_BRANCH!r}"
        )
    run_info = runs["workflow_runs"][0]
    result = {
        "run_id": run_info["id"],
        "url": run_info["html_url"],
        "head_sha": run_info["head_sha"],
        "started_at": run_info.get("run_started_at"),
        "tests": None,
        "tests_note": None,
    }
    if not with_logs:
        result["tests_note"] = "log parsing skipped (--skip-ci-logs)"
        return result

    jobs = gh_api(f"repos/{slug}/actions/runs/{run_info['id']}/jobs?per_page=100")
    job_id = None
    for job in jobs.get("jobs", []) if isinstance(jobs, dict) else []:
        if job.get("name") == CI_TEST_JOB and job.get("status") == "completed":
            job_id = job["id"]
            break
    if job_id is None:
        result["tests_note"] = (
            f"job {CI_TEST_JOB!r} not found in run {run_info['id']}"
        )
        return result
    try:
        log_text = fetch_job_log(slug, job_id)
    except CollectorError as exc:
        # A green run with unavailable logs is degradable evidence: the run
        # link still proves CI state; the totals are simply not asserted.
        # Fixed-string reason only — gh diagnostics must not leak into
        # generated public metadata.
        print(f"warning: job log unavailable: {exc}", file=sys.stderr)
        result["tests_note"] = (
            "job log unavailable in this environment; totals not asserted"
        )
        return result
    result["tests"] = parse_test_result_lines(log_text)
    if result["tests"]["seen"] == 0:
        result["tests"] = None
        result["tests_note"] = "no libtest result lines found in job log"
    return result


def parse_test_result_lines(text: str) -> dict:
    """Sum libtest 'test result:' lines from a gauntlet job log."""
    passed = failed = ignored = seen = 0
    for line in text.splitlines():
        if "test result:" not in line:
            continue
        seen += 1
        match = re.search(
            r"test result: (?:ok|FAILED)"
            r"\. (\d+) passed; (\d+) failed; (\d+) ignored",
            line,
        )
        if match:
            passed += int(match.group(1))
            failed += int(match.group(2))
            ignored += int(match.group(3))
    return {"passed": passed, "failed": failed, "ignored": ignored, "seen": seen}


def collect_release(slug: str) -> dict | None:
    """Latest published release, or None only when confirmed absent.

    Collection failures (rate limit, network, server error) propagate: under
    --strict a missing release must mean "no release exists", never "the
    API call failed" (review finding on #526).
    """
    data = gh_api(f"repos/{slug}/releases/latest")
    if not isinstance(data, dict) or not data.get("tag_name"):
        return None
    return {
        "tag": data["tag_name"],
        "url": data.get("html_url"),
        "published_at": data.get("published_at"),
    }


# ---------------------------------------------------------------------------
# Assembly


def entry(
    title: str,
    lane: str,
    state: str,
    evidence_url: str | None,
    source: str,
    source_id: str | None,
    updated_at: str | None,
    notes: str | None = None,
) -> dict:
    return {
        "title": title,
        "lane": lane,
        "state": state,
        "evidence_url": evidence_url,
        "source": source,
        "source_sha_or_id": source_id,
        "updated_at": updated_at,
        "notes": notes,
    }


def beads_to_entries(items: list[dict]) -> list[dict]:
    """Map allowlisted beads rows to status entries, dropping finished ones.

    Only {id, title, status} ever cross this boundary — descriptions and
    comments must not reach the site (plan #515 §6).
    """
    entries: list[dict] = []
    for item in items:
        status = (item.get("status") or "").lower()
        if status in BEADS_DONE_STATUSES:
            continue
        entries.append(
            entry(
                title=str(item["title"]),
                lane="Workstream board",
                state=status or "unknown",
                evidence_url=None,
                source="beads",
                source_id=str(item["id"]),
                updated_at=None,
                notes="local tracker snapshot (ids/titles/state only)",
            )
        )
    return entries


def build_payload(
    repo_root: Path,
    slug: str,
    beads: tuple[list[dict], dict],
    with_ci_logs: bool = True,
) -> dict:
    beads_items, beads_meta = beads
    issue_total, issue_items = search_issues(slug, "issue")
    pr_total, pr_items = search_issues(slug, "pr")
    ci = collect_ci(slug, with_logs=with_ci_logs)
    release = collect_release(slug)

    entries: list[dict] = beads_to_entries(beads_items)
    for item in issue_items:
        entries.append(
            entry(
                title=str(item["title"]),
                lane="Open issues",
                state="open",
                evidence_url=item.get("html_url"),
                source="github",
                source_id=f"#{item['number']}",
                updated_at=item.get("updated_at"),
            )
        )
    for item in pr_items:
        entries.append(
            entry(
                title=str(item["title"]),
                lane="Pull requests",
                state="open",
                evidence_url=item.get("html_url"),
                source="github",
                source_id=f"#{item['number']}",
                updated_at=item.get("updated_at"),
            )
        )

    tests = ci.get("tests")
    entries.append(
        entry(
            title="Latest green CI run on dev (test totals)",
            lane="CI",
            state="passing",
            evidence_url=ci["url"],
            source="github-actions",
            source_id=str(ci["run_id"]),
            updated_at=ci.get("started_at"),
            notes=(
                f"{tests['passed']} passed / {tests['failed']} failed / "
                f"{tests['ignored']} ignored ({CI_TEST_JOB})"
                if tests
                else (ci.get("tests_note") or "test totals unavailable")
            ),
        )
    )
    if release:
        entries.append(
            entry(
                title=f"Latest release {release['tag']}",
                lane="Release",
                state="published",
                evidence_url=release.get("url"),
                source="github",
                source_id=release["tag"],
                updated_at=release.get("published_at"),
            )
        )

    generated_at = utc_now()
    payload = {
        "_meta": {
            "generated_by": GENERATED_BY,
            "generated_at": generated_at,
            "schema": 1,
            "note": GENERATED_NOTE,
        },
        "generated_at": generated_at,
        "repo": slug,
        # dev tip as verified by the green CI run — NOT the local checkout
        # HEAD, which is main during promotions and the default branch on
        # scheduled runs (review finding on #526).
        "dev_head": ci["head_sha"],
        "summary": {
            "open_issues": issue_total,
            "open_pull_requests": pr_total,
            "board_items_open": sum(
                1
                for item in beads_items
                if (item.get("status") or "").lower() not in BEADS_DONE_STATUSES
            ),
            "tests": tests,
            "latest_release": release,
        },
        "sources": {
            "beads": beads_meta,
            "ci": {
                "run_id": ci["run_id"],
                "url": ci["url"],
                "head_sha": ci["head_sha"],
            },
        },
        "entries": entries,
    }
    return payload


def write_payload(output_dir: Path, payload: dict) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    out = output_dir / "progress.json"
    out.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="repository root (default: parent of this script)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="output directory (default: <repo-root>/site/data)",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="abort (exit 1) on missing or failing sources",
    )
    parser.add_argument(
        "--skip-ci-logs",
        action="store_true",
        help="skip job-log parsing for test totals",
    )
    args = parser.parse_args(argv)
    output_dir = args.output or (args.repo_root / "site" / "data")

    try:
        slug = git_repo_slug(args.repo_root)
        beads = collect_beads(args.repo_root)
        payload = build_payload(
            args.repo_root, slug, beads, with_ci_logs=not args.skip_ci_logs
        )
        out = write_payload(output_dir, payload)
    except CollectorError as exc:
        print(f"error: {exc}", file=sys.stderr)
        if args.strict:
            return 1
        print(
            "warning: continuing non-strict; no output written for this run",
            file=sys.stderr,
        )
        return 0

    summary = payload["summary"]
    print(f"wrote {out}")
    tests = summary.get("tests")
    tests_line = (
        f"tests={tests['passed']}/{tests['failed']}/{tests['ignored']} (passed/failed/ignored)"
        if tests
        else "tests=not asserted"
    )
    print(
        "open issues={open_issues} open PRs={open_pull_requests} "
        "board-open={board_items_open} ci-run={run} {tests_line}".format(
            run=payload["sources"]["ci"]["run_id"],
            tests_line=tests_line,
            **{k: v for k, v in summary.items() if k != "tests"},
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
